name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:

  Build_Docker_files:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Backend image
      run: docker build . --file Dockerfile --tag ece461-web-backend:$(date +%s)
      working-directory: backend
      
    - uses: actions/checkout@v3
    - name: Build the Frontend image
      run: docker build . --file dockerfile --tag ece461-web-frontend:$(date +%s)
      working-directory: frontend
